language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE questions_test;' -U postgres
notifications:
  email: false
env:
  global:
    secure: o718TmkdTWWFJykMHdChUhhWqQdGoAJsGCqxeNnu6Ldb3yC0MrSFyVHhpBXH6JVkZuGWkf4Gwtk6lvqzo8jGlqdbi8EfFVn+t390ABPUwhIPwoUeJCJ5D6pPYwfRIJeV3oI9+WGo22CJ2kE9cy/ZYjTqiek2iyJM/NgHxXgs53QIjB86UFefXffXz2dwo6BSJ1sB4C9dhZ9m7URS9apu0wQ/dICiT10t6SOASYLt5Zgyae24DjCHkiVPMaq5FcnRaAov0jFPS+FqWacVfbUXecEvNNrpe0jq5h1Gv/cb+Q/H4mCCE1XJnDqCJ2NtCPUyftMMTwMrihTbAn3DOz2FdaE4heLOwsYihOHSLclbweOrGI8tOck01BQPfsSrLQcSdWCF6K3LQ7BD6fML80rMXCQRJBczRbmDxyWTYDVSvs6mW/iF5QSb8QAUg4CRERPRS5TzoPzOea38gdDrZQOeE99LbEOiuXFTekhfajoSyUnZQnIpt9ZHPh+LC0vCM+qrtwPuvIFN+CcvQ7gYGZc1M25iLASQRRg3mlnZvNNiId01kgHKEK+wxcWyD7YBUa3f1bCmFXIlwkFHpakBhPKiksRbp9edlpRKsx/+YgExTHlxRLiOnrFWfZT9Wv10YWfOCsuohS9zSSyuIo+tbPudSDcxlQYtCM57Wwwzpa1VgGo=
deploy:
  provider: heroku
  api_key:
    secure: KgmM8Te04/Cg5ZVBlpX/pdZM7+Q5AHlQjk1qreBSwD8//a56XGzH+rNnknYBbi3qwYKzGOvj8BMIYKNw/gVqVWOxmfrn5VheuDnd/x1Oe8Svw4Zi+LCPDl2oePvGULG2E6m+Kc5VbtivnakhxV/79/xXqS13OK7dZDV5TFYZivkfzO5FcY8zNqEHQu/XlFuY7EjEit4eEas9wWM2JCTtU5hBKFJ7/ar3U/n7bPemWbi+PAoLKHVUp8p6iy4iUgK1u1MO+5QO4pkAyhR0vLQDBNkrzVDsVPrRTgw4Meacsh/ype1lr6aNBJwPnC3HpDmX3LVQaPIUMB1reHji6hfwOZy7BmKvG5DpS6M+/s/O01f7Fso8TxS/OZW+cMA8DRQ9GdkqswdpLN8Y9nkjhiDbxdCWeSyiE8FN4j3lUEMdy+7G2cA7PPGgZrrTe8WdeYEUR4qHq9IT+y03wNgKpqM2X317u4o1QzhuFxhi2x6zPvzLtIhVRG/oOGmDBG86uxZScOcKmr60f5FydOr1WIiqKJjIGxrmj0uxC5m5UNiClKtraKq4Ki5ihQUsUaruOlbK7yRx9Zdo+SPLsG5lgUFRcNJnP6RpPuWas+6/16rGSfpXfCRKMjWFlOctX6hQVOEIsgLM9TrsvY/0uHAcoWhMjVIm4X8PEDFKTJzmkV2D6rU=
