language: node_js
node_js:
  - "node"
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE questions_test;' -U postgres
notifications: 
  email: false
env:
  global:
    secure: "o718TmkdTWWFJykMHdChUhhWqQdGoAJsGCqxeNnu6Ldb3yC0MrSFyVHhpBXH6JVkZuGWkf4Gwtk6lvqzo8jGlqdbi8EfFVn+t390ABPUwhIPwoUeJCJ5D6pPYwfRIJeV3oI9+WGo22CJ2kE9cy/ZYjTqiek2iyJM/NgHxXgs53QIjB86UFefXffXz2dwo6BSJ1sB4C9dhZ9m7URS9apu0wQ/dICiT10t6SOASYLt5Zgyae24DjCHkiVPMaq5FcnRaAov0jFPS+FqWacVfbUXecEvNNrpe0jq5h1Gv/cb+Q/H4mCCE1XJnDqCJ2NtCPUyftMMTwMrihTbAn3DOz2FdaE4heLOwsYihOHSLclbweOrGI8tOck01BQPfsSrLQcSdWCF6K3LQ7BD6fML80rMXCQRJBczRbmDxyWTYDVSvs6mW/iF5QSb8QAUg4CRERPRS5TzoPzOea38gdDrZQOeE99LbEOiuXFTekhfajoSyUnZQnIpt9ZHPh+LC0vCM+qrtwPuvIFN+CcvQ7gYGZc1M25iLASQRRg3mlnZvNNiId01kgHKEK+wxcWyD7YBUa3f1bCmFXIlwkFHpakBhPKiksRbp9edlpRKsx/+YgExTHlxRLiOnrFWfZT9Wv10YWfOCsuohS9zSSyuIo+tbPudSDcxlQYtCM57Wwwzpa1VgGo="
